"""Stage 4 report writer — dual output (summary + per-candidate YAML records).

Two artifacts per scan:

  1. `reports/YYYY-MM-DD-scan.md`
     Human-browsable summary with a ranked table. Dewangga reads this to pick
     candidates.

  2. `reports/YYYY-MM-DD-scan/candidates/<rank>-<slug>.md`
     One file per ranked candidate, YAML frontmatter (Stage 3.5 schema) +
     prose body. Vault Stage A reads exactly one of these files when the
     user says "new audit on <slug> at <path>" and lifts YAML fields into
     `VAULT_CONTEXT.md` (Phase 2a sections 1/2/6/7).

The per-candidate YAML field layout MUST NOT drift from the Stage 3.5 schema
in the plan file — field names are the handoff contract with the vault.
"""

from __future__ import annotations

import logging
import shutil
from datetime import date
from pathlib import Path
from typing import Any

import yaml

from tvl_scanner.config import settings
from tvl_scanner.models import CandidateRecord

log = logging.getLogger(__name__)


def _fmt_tvl(tvl: float) -> str:
    if tvl >= 1_000_000:
        return f"${tvl / 1_000_000:.1f}M"
    if tvl >= 1_000:
        return f"${tvl / 1_000:.0f}K"
    return f"${int(tvl)}"


def _fmt_age(days: int) -> str:
    if days < 30:
        return f"{days}d"
    if days < 365:
        return f"{days // 30}mo"
    return f"{days // 365}y{(days % 365) // 30}mo"


def _fmt_loc(loc: int | None) -> str:
    if loc is None:
        return "?"
    if loc >= 1000:
        return f"{loc // 1000}k"
    return str(loc)


def _verification_cell(candidate: CandidateRecord) -> str:
    """Compact verification status for the summary table.

    EVM values: '✓' verified, '✗' unverified (RED FLAG), 'P' proxy, '?' not-checked
    Solana values: '✓' OtterSec-registered, '—' not-registered (neutral default)
    """
    is_solana = candidate.chain.value == "solana"
    if is_solana:
        return "✓" if candidate.is_verified else "—"
    # EVM
    if candidate.is_verified is None:
        return "?"
    if not candidate.is_verified:
        return "✗"
    if candidate.is_proxy:
        return "P"
    return "✓"


def _summary_table(candidates: list[CandidateRecord]) -> str:
    """Render the ranked summary table for the scan report."""
    lines: list[str] = []
    lines.append(
        "| Rank | Protocol | Chain | TVL | Age | LOC | Audits | Under-audited | Ver | Bounty | Priority | Record |"
    )
    lines.append(
        "|------|----------|-------|-----|-----|-----|--------|---------------|-----|--------|----------|--------|"
    )
    for i, c in enumerate(candidates, start=1):
        record_link = f"[→](./{{scan_slug}}/candidates/{i:02d}-{c.target_name}.md)"
        # "?" = no audit source was consultable, so the count is UNKNOWN.
        # "—" = we checked and found nothing. Printing "—" for both used to
        # read as "zero audits" for protocols whose audits are simply
        # published somewhere the scanner cannot see (own docs site).
        if not c.audit_record_resolved:
            audits_cell = "?"
        elif c.audit_density_score > 0:
            audits_cell = f"{c.audit_density_score}"
        else:
            audits_cell = "—"
        under_cell = "✓" if c.under_audited else ""
        bounty_cell = c.bounty_program if c.bounty_program != "none" else "—"
        lines.append(
            "| {rank} | {name} | {chain} | {tvl} | {age} | {loc} | {audits} | {under} | {ver} | {bounty} | {prio} | {link} |".format(
                rank=i,
                name=c.display_name[:40],
                chain=c.chain.value,
                tvl=_fmt_tvl(c.tvl_usd) if c.tvl_resolved else "?",
                age=_fmt_age(c.age_days),
                loc=_fmt_loc(c.loc_estimate),
                audits=audits_cell,
                under=under_cell,
                ver=_verification_cell(c),
                bounty=bounty_cell,
                prio=f"{c.priority_score:.1f}",
                link=record_link,
            )
        )
    return "\n".join(lines)


def _summary_header(candidates: list[CandidateRecord], scan_date: date) -> str:
    total = len(candidates)
    under = sum(1 for c in candidates if c.under_audited)
    chains = sorted({c.chain.value for c in candidates})
    tvl_sum = sum(c.tvl_usd for c in candidates)
    audit_dir = settings().AUDIT_DIR.rstrip("/")
    return (
        f"# TVL Scanner Report — {scan_date.isoformat()}\n\n"
        f"**Total candidates**: {total}  \n"
        f"**Under-audited** (audit_density_score ≤ 2): {under}  \n"
        f"**Chains scanned**: {', '.join(chains)}  \n"
        f"**Aggregate TVL**: {_fmt_tvl(tvl_sum)}\n\n"
        f"Generated by [tvl-scanner](https://github.com/BadGenius22/tvl-scanner). "
        f"To audit a candidate, say to Claude Code: `new audit on <target_name> at {audit_dir}/{scan_date.isoformat()}-<slug>/` — "
        f"Stage A (Phase 2a) will lift the per-candidate YAML into VAULT_CONTEXT.md.\n\n"
        f"---\n\n"
    )


def _summary_usage() -> str:
    return (
        "\n\n---\n\n"
        "## How to use this report\n\n"
        "1. Skim the ranked table above. Priority is on a 0-10 scale "
        "(tvl × 0.25 + freshness × 0.20 + audit-gap × 0.30 + activity × 0.15 + edge-match × 0.10 + bounty × 0.10).\n"
        "2. Click the `→` link on any row to open the full per-candidate record.\n"
        "3. When you want to audit one, invoke the vault Phase 2a handoff via Claude Code "
        "(see header above for the exact trigger phrase).\n"
        "4. **`TVL` column**: `?` means UNRESOLVED — DefiLlama had no usable figure, so the protocol may still hold real value. Never read it as a measured $0; verify on-chain.\n"
        "5. **`Audits` column**: a number is a resolved count, `—` means checked-and-none-found, "
        "and **`?` means UNRESOLVED** — no audit source was consultable, so the count is unknown, "
        "NOT zero. Protocols that publish audits only on their own docs site read as `?`; verify "
        "manually before believing an audit gap. Unresolved candidates get a neutral audit-gap "
        "score, so they are neither rewarded nor punished by the ranking.\n"
        "6. Skip candidates with `audit_density_score > 2` unless they are a re-audit of code changes since their last review.\n"
    )


def _candidate_body(candidate: CandidateRecord) -> str:
    """Render the human-readable body of a per-candidate file (after YAML frontmatter)."""
    lines: list[str] = []
    lines.append(f"# {candidate.display_name}")
    lines.append("")
    lines.append(f"> {candidate.why_interesting}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Chain**: {candidate.chain.value}")
    lines.append(f"- **Primary contract**: `{candidate.primary_contract}`")
    if candidate.tvl_resolved:
        lines.append(f"- **TVL**: {_fmt_tvl(candidate.tvl_usd)} ({int(candidate.tvl_usd):,})")
    else:
        lines.append(
            "- **TVL: UNRESOLVED** — DefiLlama has no usable figure for this protocol "
            "(no name-match, or it is listed with a null tvl). This is NOT a measured "
            "$0; the protocol may hold substantial value. Measure the in-scope "
            "contracts on-chain before judging whether it is worth auditing."
        )
    lines.append(f"- **Age**: {_fmt_age(candidate.age_days)} (first seen {candidate.first_seen.isoformat()})")
    if candidate.unique_users_30d is not None:
        lines.append(f"- **Unique users 30d**: {candidate.unique_users_30d:,}")
    if candidate.loc_estimate:
        lines.append(f"- **LOC estimate**: ~{candidate.loc_estimate:,}")
    if candidate.github_repo:
        lines.append(f"- **GitHub**: {candidate.github_repo}")
    if candidate.docs_url:
        lines.append(f"- **Docs**: {candidate.docs_url}")
    lines.append(f"- **Languages**: {', '.join(lang.value for lang in candidate.languages)}")
    lines.append("")

    # Verification status. Render differently per chain:
    #   EVM (Etherscan): is_verified is True/False, never None. False = red flag.
    #   Solana (OtterSec): is_verified is True (verified) or False (not in OtterSec
    #                      DB, which is the DEFAULT for most programs). False here
    #                      does NOT mean "unverified source" — it means "reproducible
    #                      build not registered". Render it as neutral informational.
    is_solana = candidate.chain.value == "solana"
    if is_solana:
        lines.append("## Reproducible build (OtterSec)")
        lines.append("")
        if candidate.is_verified:
            lines.append("- **Status**: ✓ Registered in OtterSec verified-builds DB")
            if candidate.compiler_version:
                lines.append(f"- **Verification ref**: `{candidate.compiler_version}`")
            lines.append(
                "  - The deployed program bytecode matches a reproducible build from the published source. "
                "You can trust the github_repo above represents the audited code."
            )
        else:
            lines.append("- **Status**: — Not registered in OtterSec")
            lines.append(
                "  - This is the default for most Solana programs (<20% are registered). "
                "NOT a red flag — but you cannot trust that the github_repo matches the deployed "
                "bytecode byte-for-byte without running `solana-verify` yourself."
            )
        lines.append("")
    elif candidate.is_verified is not None:
        lines.append("## On-chain verification (Etherscan V2)")
        lines.append("")
        if candidate.is_verified:
            lines.append("- **Status**: ✓ Verified")
            if candidate.contract_name:
                lines.append(f"- **Contract name**: `{candidate.contract_name}`")
            if candidate.compiler_version:
                lines.append(f"- **Compiler**: `{candidate.compiler_version}`")
            if candidate.is_proxy:
                lines.append(
                    f"- **Proxy**: ✓ EIP-1967 proxy detected → impl `{candidate.proxy_impl_address or 'not set'}`"
                )
                lines.append(
                    "  - ⚠ When auditing, check BOTH the proxy and the implementation. "
                    "Unverified implementation behind a verified proxy is a common obfuscation pattern."
                )
        else:
            lines.append("- **Status**: ✗ UNVERIFIED")
            lines.append(
                "  - ⚠ **Red flag**: the deployed bytecode is not verified on Etherscan. "
                "Either the team hasn't verified yet (ultra-fresh deployment) or they're hiding source. "
                "Do not audit without source — confirm the team has a plan to verify before committing time."
            )
        lines.append("")

    if candidate.bounty_program != "none":
        lines.append("## Bounty program")
        lines.append("")
        lines.append(f"- **Platform**: {candidate.bounty_program}")
        if candidate.bounty_url:
            lines.append(f"- **URL**: {candidate.bounty_url}")
        if candidate.bounty_max_payout_usd:
            lines.append(f"- **Max payout**: ${candidate.bounty_max_payout_usd:,}")
        lines.append("")

    lines.append("## Audit history")
    lines.append("")
    if not candidate.audit_record_resolved:
        lines.append(
            "- **Audit record: UNRESOLVED** — no audit source was consultable "
            "(no DefiLlama audit field, no GitHub repo, no audit URL cited in the "
            "bounty prose). The density score below is *unknown*, not zero. Many "
            "protocols publish audits only on their own docs site, which this "
            "scanner cannot see. **Verify manually before treating as a gap.**"
        )
    lines.append(f"- **Audit density score**: {candidate.audit_density_score} "
                 f"({'unknown — see above' if not candidate.audit_record_resolved else 'under-audited' if candidate.under_audited else 'already audited'})")
    if candidate.defillama_audit_count is not None:
        lines.append(
            f"- **DefiLlama audit count**: {candidate.defillama_audit_count} "
            f"(from /protocol/{{slug}} detail)".replace("{slug}", candidate.defillama_slug or "")
        )
    if candidate.defillama_audit_note:
        lines.append(f"- **DefiLlama audit note**: *{candidate.defillama_audit_note}*")
    if not candidate.audit_sources_found:
        lines.append(
            "- **Audit record unresolved** — nothing to check, see caveat above."
            if not candidate.audit_record_resolved
            else "- **No audits found** in any checked source."
        )
    else:
        lines.append("- Sources found:")
        for src in candidate.audit_sources_found:
            title = src.title or str(src.url or src.source)
            lines.append(f"  - `{src.source}` ({src.weight}pt): {title}")
    lines.append("")

    lines.append("## Priority breakdown")
    lines.append("")
    lines.append(f"- **Composite**: {candidate.priority_score:.2f} / 10")
    lines.append(f"  - tvl: {candidate.tvl_score:.1f} × 0.25")
    lines.append(f"  - freshness: {candidate.freshness_score:.1f} × 0.20")
    lines.append(f"  - audit_gap: {candidate.audit_gap_score:.1f} × 0.30")
    lines.append(f"  - activity: {candidate.activity_score:.1f} × 0.15")
    lines.append(f"  - edge_match: {candidate.edge_match_score:.1f} × 0.10 "
                 f"(keywords: {', '.join(candidate.edge_match_keywords) or 'none'})")
    lines.append(f"  - bounty: {candidate.bounty_score:.1f} × 0.10")
    lines.append("")

    lines.append("## Suggested focus areas")
    lines.append("")
    for area in candidate.focus_areas_suggested:
        lines.append(f"- {area}")
    lines.append("")

    lines.append("## Vault handoff (Phase 2a)")
    lines.append("")
    lines.append("To audit this candidate, say to Claude Code:")
    lines.append("")
    audit_dir = settings().AUDIT_DIR.rstrip("/")
    lines.append(
        f"> `new audit on {candidate.target_name} at {audit_dir}/"
        f"{candidate.scan_date.isoformat()}-{candidate.target_name}/`"
    )
    lines.append("")
    lines.append(
        "Stage A will read this file, lift the YAML frontmatter fields into "
        "VAULT_CONTEXT.md (sections 1/2/6/7), grep the vault for applicable "
        "patterns and case studies (sections 3/4), and propose the full file "
        "per Phase 2a safety gates."
    )
    lines.append("")
    return "\n".join(lines)


def _frontmatter_dict(candidate: CandidateRecord) -> dict[str, Any]:
    """Build the YAML frontmatter dict. Field names MUST match Stage 3.5 schema."""
    return {
        # --- Section 1: Target Identification ---
        "target_name": candidate.target_name,
        "display_name": candidate.display_name,
        "protocol_type": candidate.protocol_type,
        "languages": [lang.value for lang in candidate.languages],
        "chains": [candidate.chain.value],
        "inferred_platform": candidate.inferred_platform,
        "inferred_mode": candidate.inferred_mode,
        # --- Section 2: Prior Audits ---
        "audit_density_score": candidate.audit_density_score,
        "audit_sources_found": [
            {
                "source": src.source,
                "url": str(src.url) if src.url else None,
                "title": src.title,
                "published_at": src.published_at.isoformat() if src.published_at else None,
            }
            for src in candidate.audit_sources_found
        ],
        "under_audited": candidate.under_audited,
        # False = no audit source was consultable, so audit_density_score is
        # UNKNOWN rather than zero. Lifted into the vault so a downstream audit
        # never reads an unresolved record as a confirmed audit gap.
        "audit_record_resolved": candidate.audit_record_resolved,
        # --- Section 6: Suggested Focus Areas ---
        "edge_match_keywords": candidate.edge_match_keywords,
        "focus_areas_suggested": candidate.focus_areas_suggested,
        # --- Section 7: Submission Platform Context ---
        "bounty_program": candidate.bounty_program,
        "bounty_url": str(candidate.bounty_url) if candidate.bounty_url else None,
        "bounty_max_payout_usd": candidate.bounty_max_payout_usd,
        # --- Scanner metadata (not lifted but useful) ---
        "tvl_usd": candidate.tvl_usd,
        # False = unmeasured; tvl_usd is a 0.0 placeholder, not a real zero.
        "tvl_resolved": candidate.tvl_resolved,
        "first_seen": candidate.first_seen.isoformat(),
        "age_days": candidate.age_days,
        "unique_users_30d": candidate.unique_users_30d,
        "github_repo": str(candidate.github_repo) if candidate.github_repo else None,
        "loc_estimate": candidate.loc_estimate,
        "docs_url": str(candidate.docs_url) if candidate.docs_url else None,
        # Real on-chain contract resolved from the DefiLlama detail endpoint
        # (chain-qualified). None for catalog candidates whose address couldn't
        # be resolved (BSC free-tier, Solana, no detail address) and for pool
        # candidates (whose `address` is already the real contract).
        "onchain_address": candidate.onchain_address,
        "primary_contract": candidate.primary_contract,
        "priority_score": candidate.priority_score,
        "why_interesting": candidate.why_interesting,
        "scan_date": candidate.scan_date.isoformat(),
        # --- Etherscan V2 verification (EVM only; None on Solana/synthetic) ---
        "is_verified": candidate.is_verified,
        "contract_name": candidate.contract_name,
        "is_proxy": candidate.is_proxy,
        "proxy_impl_address": candidate.proxy_impl_address,
        "compiler_version": candidate.compiler_version,
        # --- DefiLlama audit history deep enrichment ---
        "defillama_audit_count": candidate.defillama_audit_count,
        "defillama_audit_note": candidate.defillama_audit_note,
    }


def write_candidate_file(
    candidate: CandidateRecord, rank: int, out_dir: Path
) -> Path:
    """Write one per-candidate file to `<out_dir>/candidates/<rank>-<slug>.md`."""
    candidates_dir = out_dir / "candidates"
    candidates_dir.mkdir(parents=True, exist_ok=True)
    path = candidates_dir / f"{rank:02d}-{candidate.target_name}.md"

    frontmatter = _frontmatter_dict(candidate)
    yaml_text = yaml.safe_dump(
        frontmatter, sort_keys=False, default_flow_style=False, allow_unicode=True
    )
    body = _candidate_body(candidate)
    content = f"---\n{yaml_text}---\n\n{body}"
    path.write_text(content)
    return path


def write_report(
    candidates: list[CandidateRecord],
    scan_date: date,
    *,
    reports_dir: Path | None = None,
    label: str = "scan",
) -> tuple[Path, list[Path]]:
    """Write both the summary report and per-candidate files.

    Returns (summary_path, candidate_file_paths).

    BUGFIX (post-Batch I.2): the per-candidate directory is purged before
    writing new files. Without this, multiple scans on the same date
    accumulated files like `01-pendle.md` (v0.4.0) + `01-jagpool-staked-sol.md`
    (v0.4.1) side-by-side, making the folder visually misleading even
    though the summary table was correct. The cleanup wipes the
    `<scan_slug>/candidates/` subdirectory entirely before recreating it.
    The summary `.md` itself is naturally overwritten so doesn't need
    explicit cleanup.
    """
    s = settings()
    reports_dir = reports_dir or s.reports_path
    reports_dir.mkdir(parents=True, exist_ok=True)
    scan_slug = f"{scan_date.isoformat()}-{label}"

    # Purge stale per-candidate files from prior scans on the same date.
    out_dir = reports_dir / scan_slug
    candidates_dir = out_dir / "candidates"
    if candidates_dir.exists():
        shutil.rmtree(candidates_dir)

    # Per-candidate files
    candidate_paths: list[Path] = []
    for i, candidate in enumerate(candidates, start=1):
        candidate_paths.append(write_candidate_file(candidate, i, out_dir))

    # Summary report
    summary_path = reports_dir / f"{scan_slug}.md"
    body = (
        _summary_header(candidates, scan_date)
        + _summary_table(candidates).replace("{scan_slug}", scan_slug)
        + _summary_usage()
    )
    summary_path.write_text(body)

    log.info(
        "wrote %s and %d per-candidate files under %s",
        summary_path,
        len(candidate_paths),
        out_dir,
    )
    return summary_path, candidate_paths
